config/routes.rb
Rails.application.routes.draw do
  
resources :cannabis
resources :cannabi

root to: 'cannabis#index'
root to: 'cannabis#new'
root to: 'cannabis#edit'
root to: 'cannabis#show'
# resources :users  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cannabis.rb
class Cannabis < ApplicationRecord
      # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
end

app/models/user.rb
class User < ApplicationRecord
    # devise :database_authenticatable, :registerable,
    #        :recoverable, :remeberable, :trackable, :vaildatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # before_action :authenticate_user!
end

app/controllers/cannabis_controller.rb
class CannabisController < ApplicationController

    def index 
        @cannabi = Cannabis.all
        render :index
    end

    def show
        @cannabi = Cannabis.find(params[:id])
    end

    def new
        @cannabi = Cannabis.new

        render :new
    end

    def create
        cannabi_params = params.require(:cannabis).permit(:strain, :img_url, :origin, :flag_url, :data, :lat, :lon)
        @cannabi = Cannabis.new(cannabi_params)

        if @cannabi.save
            redirect_to cannabis_path(@cannabi)
        else
            render :new
        end
    end

    def edit
        @cannabi = Cannabis.find(params[:id])
    end

    def update
        @cannabi = Cannabis.find(params[:id])

        if @cannabi.update_attr(cannabi_params)
            flash[:success] = "Cannabis updated!"
            redirect_to cannabi_path
        else
            render :edit
        end
    end

    def destroy
        @cannabi = Cannabis.find(params[:id]).destroy
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cannabis_helper.rb
module CannabisHelper
end

app/views/cannabis/_form.html.erb
<%= form_for @cannabi, url: "/cannabis" do |f| %>

    <%= f.text_field :strain, placeholder: "name" %>
    <br />
    <%= f.text_field :data, placeholder: "description" %>
    <br />
    <%= f.text_field :img_url, placeholder: "cannabis image" %>
    <br />
    <%= f.text_field :origin, placeholder: "place of origin" %>
    <br />


<h1><%= @cannabi.strain %></h1>


    <div class='dna'></div>

    <h2> Origin </h2> 
    <%= @cannabi.origin %>



    <%= button_to "Create #{@cannabi.strain}", cannabis_path, method: :edit %>

<% end %>

app/views/cannabis/edit.html.erb
<div class="topnav">
  <%= link_to "Home Page", cannabis_path %>
  <%= link_to "Create Page", edit_cannabi_path %>
</div>

<h1> Create a Strain </h1>

<img src="http://bestanimations.com/Nature/Flora/Hemp/animated-hemp-marijuana-gif-14.gif" />
<%= form_for cannabi_path do |f| %>
    <h2>Strain:</h2>
    <%= f.text_field :strain %><br />
    <h2>Origin:</h2>
    <%= f.text_field :origin %><br />
    <h2>Description:</h2>
    <%= f.text_field :data %><br />
    <h2>Image:</h2>
    <%= f.text_field :img_url %><br /><br />
    <%= f.submit "Submit" %>      
<% end %>

app/views/cannabis/index.html.erb
<h1> Cannabis Strains </h1>
<div class='science'>
    <p>Welcome to the different variations of marijuana!</p>
</div>

<div class="effect2">
    <p>Marijuana strains stem --<em>no pun intended</em>-- from all over the world. The use of the main ingredient in marijuana (THC) is highly recognized in the medical field for keeping a lot of ailments under control.</p>
</div>
<div class="effect3">
    <p>
    Despensaries are the safest way to obtain medical marijuana. Theres a high demand for it marijuana worldwide.
    If there is a strain people should know about feel free to provide the info for others.
    Cheers!! 🍻 
    </p>
</div>

<div class="effect1">
    <h2> Select a Strain </h2> 

<div class ="container">    
    <% @cannabi.each do |strain| %>
        <div class="strains">
        <%= link_to "Strain:", cannabi_path(strain) %>
        <%= strain.strain %> <br />
        </div>
    <% end %>
</div>


</div>    

<footer>Copyright &copy Todd McIver </footer>
    

app/views/cannabis/new.html.erb
<h1> Create A New Strain of Cannabis </h1>

<%= render partial: 'form' %>

<h2> <%= link_to 'List of Cannabis', new_cannabi_path %> </h2>

app/views/cannabis/show.html.erb
<div class="topnav">
  <%= link_to "Home Page", cannabis_path %>
  <%= link_to "Create Page", new_cannabi_path %>
  <%= link_to "Delete", @cannabi, method: :delete,
                                  message: {confirm: "You sure?"} %>
</div>

<h1><%= @cannabi.strain %></h1>

<h2> Strain </h2>
<div id="strain">
  <%= image_tag (@cannabi.img_url) %>
</div>

<div class='dna'></div>

<h2> Description </h2> 
<div id="data">
<%= @cannabi.data %>
</div> 

<div class='dna'></div>

<h2> Origin </h2> 
<%= @cannabi.origin %>
<%= image_tag (@cannabi.flag_url) %>

<h3> Location </h3>
<!DOCTYPE html>
<html>
  <head>
  <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
  <script src='https://api.mapbox.com/mapbox.js/v3.1.1/mapbox.js'></script>
  <link href='https://api.mapbox.com/mapbox.js/v3.1.1/mapbox.css' rel='stylesheet' />

  </head>
  <body>
  <div class="google-map">
  <div id='map' data="<%= @cannabi %>"></div>
  <div id='map' class='dark'></div>
  <script>
    L.mapbox.accessToken = 'pk.eyJ1IjoidG1ja2VubmExIiwiYSI6ImNqa215bmJndzBnYWMzcG96bXB0cG54enoifQ.QBFnzyV6VVqaNwjOPeqHBw';
    var map = new mapbox.Map({
      container: 'map', 
      style: 'mapbox://styles/mapbox/streets-v9', 
      center: [<%= @cannabi.lon %>,<%= @cannabi.lat %>], 
      zoom: 5
      });
  </script>
  </head>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CannabisApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>